import { useEffect, useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { AlertCircle, RefreshCw, ShieldCheck } from "lucide-react";

interface MfaChallengeProps {
  account: string;
  onVerified: () => void;
  onBack: () => void;
  compact?: boolean;
}

const CODE_LENGTH = 6;

export default function MfaChallenge({ account, onVerified, onBack, compact }: MfaChallengeProps) {
  const [code, setCode] = useState<string[]>(Array(CODE_LENGTH).fill(""));
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const [secondsLeft, setSecondsLeft] = useState(30);
  const inputs = useRef<Array<HTMLInputElement | null>>([]);

  useEffect(() => {
    inputs.current[0]?.focus();
  }, []);

  useEffect(() => {
    const t = setInterval(() => setSecondsLeft((s) => (s <= 1 ? 30 : s - 1)), 1000);
    return () => clearInterval(t);
  }, []);

  const setDigit = (index: number, value: string) => {
    const digits = value.replace(/\D/g, "");
    const next = [...code];
    if (!digits) {
      next[index] = "";
      setCode(next);
      return;
    }
    for (let i = 0; i < digits.length && index + i < CODE_LENGTH; i++) {
      next[index + i] = digits[i];
    }
    setCode(next);
    inputs.current[Math.min(index + digits.length, CODE_LENGTH - 1)]?.focus();
  };

  const handleKeyDown = (index: number, e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Backspace" && !code[index] && index > 0) inputs.current[index - 1]?.focus();
    if (e.key === "Enter") handleVerify();
  };

  const handleVerify = (e?: React.FormEvent) => {
    e?.preventDefault();
    if (code.join("").length !== CODE_LENGTH) {
      setError("Enter the 6-digit code from your authenticator app.");
      return;
    }
    setError("");
    setLoading(true);
    // Prototype: any 6-digit code is accepted. Production must verify server-side.
    setTimeout(() => {
      setLoading(false);
      onVerified();
    }, 700);
  };

  return (
    <form onSubmit={handleVerify} className={compact ? "space-y-4" : "space-y-5"}>
      <div className="text-center space-y-1">
        <div className="w-11 h-11 rounded-xl bg-accent/10 flex items-center justify-center mx-auto">
          <ShieldCheck className="w-5 h-5 text-accent" />
        </div>
        <h4 className="font-heading font-bold text-base">MFA Verification</h4>
        <p className="text-xs text-muted-foreground">Enter the code from your authenticator app to complete sign in.</p>
        <p className="text-xs text-muted-foreground">
          Account: <span className="font-medium text-foreground">{account}</span>
        </p>
      </div>

      <div className="space-y-1.5">
        <div className="flex items-baseline gap-2">
          <span className="text-xs font-semibold text-foreground">1</span>
          <span className="text-xs font-semibold text-foreground">Enter verification code</span>
        </div>
        <p className="text-[11px] text-muted-foreground pl-5">6-digit dynamic code generated by your authenticator.</p>
        <div className="flex gap-1.5 pt-1">
          {code.map((digit, i) => (
            <Input
              key={i}
              ref={(el) => (inputs.current[i] = el)}
              value={digit}
              inputMode="numeric"
              autoComplete="one-time-code"
              maxLength={CODE_LENGTH}
              aria-label={`Digit ${i + 1}`}
              onChange={(e) => setDigit(i, e.target.value)}
              onKeyDown={(e) => handleKeyDown(i, e)}
              className="h-11 w-full px-0 text-center text-lg font-heading font-bold"
            />
          ))}
        </div>
      </div>

      {error && (
        <div className="flex items-center gap-2 text-xs text-destructive bg-destructive/10 rounded-md p-2.5">
          <AlertCircle className="w-4 h-4 shrink-0" />
          {error}
        </div>
      )}

      <Button type="submit" className="w-full h-9 text-sm" disabled={loading}>
        {loading ? <RefreshCw className="w-4 h-4 animate-spin mr-2" /> : null}
        Verify & Login
      </Button>

      <div className="space-y-1.5 text-center">
        <button
          type="button"
          onClick={() => {
            setCode(Array(CODE_LENGTH).fill(""));
            setError("");
            setSecondsLeft(30);
            inputs.current[0]?.focus();
          }}
          className="inline-flex items-center gap-1.5 text-xs font-medium text-accent hover:underline"
        >
          <RefreshCw className="w-3 h-3" /> Refresh verification
        </button>

        <button
          type="button"
          onClick={onBack}
          className="block w-full text-xs text-muted-foreground hover:text-foreground"
        >
          Back to password login
        </button>
      </div>
    </form>
  );
}
