import { useEffect, useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { AlertCircle, RefreshCw, ShieldCheck } from "lucide-react";

interface MfaChallengeProps {
  account: string;
  onVerified: () => void;
  onBack: () => void;
}

const CODE_LENGTH = 6;

export default function MfaChallenge({ account, onVerified, onBack }: MfaChallengeProps) {
  const [code, setCode] = useState<string[]>(Array(CODE_LENGTH).fill(""));
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const [secondsLeft, setSecondsLeft] = useState(30);
  const inputs = useRef<Array<HTMLInputElement | null>>([]);

  useEffect(() => {
    inputs.current[0]?.focus();
  }, []);

  useEffect(() => {
    const t = setInterval(() => setSecondsLeft((s) => (s <= 1 ? 30 : s - 1)), 1000);
    return () => clearInterval(t);
  }, []);

  const setDigit = (index: number, value: string) => {
    const digits = value.replace(/\D/g, "");
    if (!digits) {
      const next = [...code];
      next[index] = "";
      setCode(next);
      return;
    }
    const next = [...code];
    for (let i = 0; i < digits.length && index + i < CODE_LENGTH; i++) {
      next[index + i] = digits[i];
    }
    setCode(next);
    const focusAt = Math.min(index + digits.length, CODE_LENGTH - 1);
    inputs.current[focusAt]?.focus();
  };

  const handleKeyDown = (index: number, e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Backspace" && !code[index] && index > 0) {
      inputs.current[index - 1]?.focus();
    }
  };

  const handleVerify = (e: React.FormEvent) => {
    e.preventDefault();
    const value = code.join("");
    if (value.length !== CODE_LENGTH) {
      setError("Enter the 6-digit code from your authenticator app.");
      return;
    }
    setError("");
    setLoading(true);
    setTimeout(() => {
      setLoading(false);
      // Prototype: any 6-digit code is accepted. Production must verify server-side.
      onVerified();
    }, 600);
  };

  return (
    <form onSubmit={handleVerify} className="space-y-5">
      <div className="space-y-2">
        <div className="w-12 h-12 rounded-xl bg-accent/10 flex items-center justify-center">
          <ShieldCheck className="w-6 h-6 text-accent" />
        </div>
        <h2 className="font-heading text-xl font-bold text-foreground">Two-factor authentication</h2>
        <p className="text-sm text-muted-foreground">
          Enter the verification code generated by your authenticator app to finish signing in.
        </p>
        <p className="text-sm text-muted-foreground">
          Verifying account: <span className="font-medium text-foreground">{account}</span>
        </p>
      </div>

      <div className="space-y-2">
        <div className="flex items-start gap-2">
          <span className="text-sm font-semibold text-foreground">1</span>
          <div className="space-y-1">
            <p className="text-sm font-semibold text-foreground">Enter verification code</p>
            <p className="text-xs text-muted-foreground">Type the 6-digit dynamic code from your authenticator.</p>
          </div>
        </div>
        <div className="flex gap-2 pt-1">
          {code.map((digit, i) => (
            <Input
              key={i}
              ref={(el) => (inputs.current[i] = el)}
              value={digit}
              inputMode="numeric"
              autoComplete="one-time-code"
              maxLength={CODE_LENGTH}
              aria-label={`Digit ${i + 1}`}
              onChange={(e) => setDigit(i, e.target.value)}
              onKeyDown={(e) => handleKeyDown(i, e)}
              className="h-14 w-full text-center text-xl font-heading font-bold px-0"
            />
          ))}
        </div>
      </div>

      {error && (
        <div className="flex items-center gap-2 text-sm text-destructive bg-destructive/10 rounded-md p-3">
          <AlertCircle className="w-4 h-4 shrink-0" />
          {error}
        </div>
      )}

      <Button type="submit" className="w-full h-11" disabled={loading}>
        {loading ? "Verifying…" : "Verify & Sign In"}
      </Button>

      <div className="space-y-2 text-center">
        <button
          type="button"
          onClick={() => {
            setCode(Array(CODE_LENGTH).fill(""));
            setError("");
            setSecondsLeft(30);
            inputs.current[0]?.focus();
          }}
          className="inline-flex items-center gap-1.5 text-sm font-medium text-accent hover:underline"
        >
          <RefreshCw className="w-3.5 h-3.5" /> Refresh verification
        </button>
        <p className="text-xs text-muted-foreground">Code refreshes in {secondsLeft}s</p>
        <button type="button" onClick={onBack} className="block w-full text-sm text-muted-foreground hover:text-foreground">
          Back to password login
        </button>
      </div>
    </form>
  );
}
